repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.5
    hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.5.12
  hooks:
    # Update the uv lockfile
    - id: uv-lock
  
