"""Init revision

Revision ID: 27dbff67ab6f
Revises: 2bd4c0e99504
Create Date: 2024-12-31 18:48:19.253121

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27dbff67ab6f"
down_revision: Union[str, None] = "2bd4c0e99504"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "user", "users", ["id"], ["id"], referent_schema="auth")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    # ### end Alembic commands ###
