"""folder_id is optional on bookmark

Revision ID: e154a0e8e33b
Revises: 27dbff67ab6f
Create Date: 2025-01-02 18:56:24.413174

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e154a0e8e33b"
down_revision: Union[str, None] = "27dbff67ab6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bookmark", "folder_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bookmark", "folder_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
